### ISSUE TITLE
Compilation fails: cannot find function `encode` in crate `hex`

### ISSUE THREAD

**Issue by luca-aurelia** [purpleprotocol/graphlib#53]
Hey folks,

Thanks for your work on graphlib! I love how simple and straightforward it is.

I'm running into a snag when I try and compile:

```
error[E0425]: cannot find function `encode` in crate `hex`
 --> /Users/noisemachines/.cargo/registry/src/github.com-1ecc6299db9ec823/graphlib-0.6.2/src/vertex_id.rs:9:40
  |
9 |         write!(f, "VertexId({})", hex::encode(self.0))
  |                                        ^^^^^^ not found in `hex`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `graphlib` due to previous error
```

I'm seeing this on Rust 1.55 stable, as well as Rust 1.54. Downgrading to graphlib 0.5.3 fixes the issue.

Here's a small repo that reproduces the error:
https://github.com/photon-garden/reproduce-graphlib-compilation-error

You can see it by cloning the repo and running `cargo run` or `cargo run --release`.

Let me know if I can help with anything else!

**Comment by dougli1sqrd** [comment]
I'm getting this also! I think this is, in part, because I'm working in a `no_std` environment. And the hex crate has `#[cfg(feature = "alloc")]` above the `hex::encode()` function because it returns `String`, which I think in my `no_std` environment is false, so this function is turned off.

I'm not sure what the best fix could be in a `no_std` environment. The `ToHex` trait more directly is probably what will be needed, but in a way that doesn't allocate. It looks like in graphlib this is just making a debug representation of the the VertexId.

**Comment by dougli1sqrd** [comment]
Since we know that the `VertexId` is of defined length: `[u8; 16]`, I think we can actually create a `&str` without allocation:

```rust
impl core::fmt::Debug for VertexId {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        let mut buff: [u8; 32] = [0 as u8; 32];
        let _ = hex::encode_to_slice(self.0, &mut buff);
        let s = core::str::from_utf8(&buff).unwrap();
        write!(f, "VertexId({})", s)
    }
}
```

First we can make a buffer that is twice the length of the `VertexId` since one hex represents 4 bits, but that will be displayed as a single char, or 8 bits.

Then we can use the `encode_to_slice` function which will fill the buffer with `u8` representing hex chars. Then `core::str::from_utf8` will convert the buffer into a `&str` which goes into the `write!` macro.
